---
title: "zajęcia 12 Variants"
author: "Magdalena_Chomiak"
---

# Instalowanie pakietów

```{r}

packages <- (c("VariantAnnotation", "GenomicRanges", "AnnotationHub"))
BiocManager::install(packages)

```

# Wczytywanie pakietów

```{r}

library(VariantAnnotation)
library(GenomicRanges)
library(AnnotationHub)
```

# Wczytywanie i eksploracja danych

```{r}
#wczytanie ścieżki do pliku 
fl <- system.file("extdata","chr22.vcf.gz", package="VariantAnnotation")
#wczytanie pliku 
vcf <-readVcf(fl,"hg19")
#podstawowe informacje o pliku 
vcf
```

# Analiza jakości

```{r}
summary(qual(vcf))
```

# Filtrowanie wariantów

```{r}
vcf_filtered <- vcf[!is.na(qual(vcf)) & qual(vcf) >99, ]
vcf_filtered
summary(qual(vcf_filtered))
```

# Anotacja wariantów

```{r}
BiocManager::install("TxDb.Hsapiens.UCSC.hg19.knownGene")

library(TxDb.Hsapiens.UCSC.hg19.knownGene)
txdb <- TxDb.Hsapiens.UCSC.hg19.knownGene

```

```{r}
gr <- rowRanges(vcf_filtered)
loc_anno <- locateVariants(gr, txdb, AllVariants())
head(loc_anno)
```

-   problem z niedopasowaniem nazw chromosomów i poziomów sekwencji pomiędzy obiektem `gr` (pochodzącym z `vcf_filtered`) a bazą danych `txdb` (TxDb.Hsapiens.UCSC.hg19.knownGene)
